// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./KeyValue";

export type InterceptedRequest = { id: string, timestamp: string, method: string, url: string, host: string, path: string, headers: Array<KeyValue>, body: string, status: number, responseHeaders: Array<KeyValue>, responseBody: string, durationMs: bigint, };
