export interface DocEndpoint {
  method: string;
  path: string;
  params: string;
  bodyExample: string;
  responseExample: string;
  name: string;
}

export function formatDoc(requests: DocEndpoint[], collectionName: string): string {
  const parts: string[] = [
    `# ${collectionName} API Documentation`,
    "",
    "> Auto-generated by Kite API Client",
    "",
    "## Endpoints",
    "",
  ];

  for (const req of requests) {
    parts.push(`### ${req.method} ${req.path} — ${req.name}`);
    parts.push("");
    if (req.params) {
      parts.push(`**Query Parameters:** ${req.params}`);
      parts.push("");
    }
    if (req.bodyExample) {
      parts.push("**Example Request:**");
      parts.push("```json");
      parts.push(req.bodyExample);
      parts.push("```");
      parts.push("");
    }
    if (req.responseExample) {
      parts.push("**Example Response:**");
      parts.push("```json");
      parts.push(req.responseExample);
      parts.push("```");
      parts.push("");
    }
    parts.push("---");
    parts.push("");
  }

  return parts.join("\n");
}
