import { describe, it, expect } from "vitest";
import { formatDoc } from "./doc-generator";
import type { DocEndpoint } from "./doc-generator";

describe("formatDoc", () => {
  const emptyEndpoint: DocEndpoint = {
    name: "Test",
    method: "GET",
    path: "/test",
    params: "",
    bodyExample: "",
    responseExample: "",
  };

  it("includes collection name in title", () => {
    const result = formatDoc([emptyEndpoint], "My API");
    expect(result).toContain("# My API API Documentation");
  });

  it("includes endpoint method and path", () => {
    const result = formatDoc([emptyEndpoint], "Test");
    expect(result).toContain("### GET /test");
  });

  it("includes query parameters when present", () => {
    const endpoint: DocEndpoint = { ...emptyEndpoint, params: "page=1&limit=10" };
    const result = formatDoc([endpoint], "Test");
    expect(result).toContain("**Query Parameters:** page=1&limit=10");
  });

  it("omits query parameters section when empty", () => {
    const result = formatDoc([emptyEndpoint], "Test");
    expect(result).not.toContain("Query Parameters");
  });

  it("includes body example when present", () => {
    const endpoint: DocEndpoint = {
      ...emptyEndpoint,
      bodyExample: '{"key": "value"}',
    };
    const result = formatDoc([endpoint], "Test");
    expect(result).toContain("**Example Request:**");
    expect(result).toContain('{"key": "value"}');
  });

  it("omits body example section when empty", () => {
    const result = formatDoc([emptyEndpoint], "Test");
    expect(result).not.toContain("Example Request");
  });

  it("includes response example when present", () => {
    const endpoint: DocEndpoint = {
      ...emptyEndpoint,
      responseExample: '{"id": 1}',
    };
    const result = formatDoc([endpoint], "Test");
    expect(result).toContain("**Example Response:**");
    expect(result).toContain('{"id": 1}');
  });

  it("omits response example section when empty", () => {
    const result = formatDoc([emptyEndpoint], "Test");
    expect(result).not.toContain("Example Response");
  });

  it("handles multiple endpoints", () => {
    const endpoints: DocEndpoint[] = [
      { name: "A", method: "GET", path: "/a", params: "", bodyExample: "", responseExample: "" },
      { name: "B", method: "POST", path: "/b", params: "", bodyExample: "", responseExample: "" },
    ];
    const result = formatDoc(endpoints, "Multi");
    expect(result).toContain("### GET /a");
    expect(result).toContain("### POST /b");
  });

  it("includes auto-generated header", () => {
    const result = formatDoc([emptyEndpoint], "Test");
    expect(result).toContain("Auto-generated by Kite API Client");
  });

  it("includes separators between endpoints", () => {
    const endpoints: DocEndpoint[] = [
      { name: "A", method: "GET", path: "/a", params: "", bodyExample: "", responseExample: "" },
      { name: "B", method: "GET", path: "/b", params: "", bodyExample: "", responseExample: "" },
    ];
    const result = formatDoc(endpoints, "Test");
    expect(result).toContain("---");
  });

  it("handles empty endpoint list", () => {
    const result = formatDoc([], "Empty");
    expect(result).toContain("# Empty API Documentation");
    expect(result).not.toContain("###");
  });
});